### ISSUE TITLE
Not Enough Non-NaN Values for Interpolation

### ISSUE THREAD

**Issue by cocohzy** [ArtLabss/tennis-tracking#41]
Traceback (most recent call last):
  File "/content/drive/MyDrive/tennis/tennis-tracking-main/predict_video.py", line 274, in <module>
    coords = interpolation(coords)
  File "/content/drive/MyDrive/tennis/tennis-tracking-main/detection.py", line 469, in interpolation
    xxx[nons]= np.interp(yy(nons), yy(~nons), xxx[~nons])
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 1599, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty

**Comment by Sean-MA** [comment]
Hello, have you solved this issue? I have the similar issue when I use my own tennis video. It seems caused by no tennis is detected?
