### ISSUE TITLE
Error Running Pedict.py on Colab

### ISSUE THREAD

**Issue by mdhwn21** [ArtLabss/tennis-tracking#44]
**Describe the bug**
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/tennis-tracking/predict_video.py", line 73, in <module>
    m.load_weights(save_weights_path)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_api.py", line 268, in load_weights
    raise ValueError(
ValueError: File format not supported: filepath=WeightsTracknet/model.1. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files.

**To Reproduce**
1. Follow steps for running project on colab and the above error is generated. 

**Expected behavior**
Predict.py to run without errors. 

**Desktop (please complete the following information):**
 -  Google Colab on chrome 

**Additional context**
I think the documentation needs to be updated.

**Comment by sorker** [comment]
Did you solve the problem?

**Comment by Parc-Ferme** [comment]
I identified that the file format model.1 is incompatible with Keras. To address this, I updated the file format using the command:
"mv model.1 model.h5"

I also updated the save_weights_path in the 'predict_video.py' file accordingly.

**Comment by Yasmine-bj** [comment]
I made these changes, but it still doesn't work on Google Colab. @Parc-Ferme , did that work for you?

**Comment by Parc-Ferme** [comment]
I tried running it on Google Colab again, and it seems to be working. Could you double-check and let me know if you see any issues @Yasmine-bj ? 
• File Renaming: Rename the file to “model.h5” and remove any extensions after “.h5”.
• Code Modification: Update the file name in “predict_video.py”.
• GPU Selection: Choose T4 GPU in Colab.

**Comment by Yasmine-bj** [comment]
Hi @Parc-Ferme, thanks for your quick response, it worked. It seems I made a mistake with the folder directory. Thank you for your help!

**Comment by AyushSonuu** [comment]
@Yasmine-bj can you help in running this if you have succeeded.
